"""
OASIS - M3 → M4 Origin Loader

Loads probable spill-origin points generated by the M3 drift module.
"""

import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]

ORIGINS_FILE = (
    PROJECT_ROOT
    / "data"
    / "metadata"
    / "probable_origins.json"
)


def load_probable_origins():
    """Load candidate spill origins produced by M3."""

    if not ORIGINS_FILE.exists():
        raise FileNotFoundError(
            f"M3 origin file not found at: {ORIGINS_FILE}"
        )

    with open(ORIGINS_FILE, "r", encoding="utf-8") as file:
        data = json.load(file)

    return data


if __name__ == "__main__":
    origins = load_probable_origins()

    print(f"Loaded {len(origins)} probable origins.")

    for origin in origins:
        print(
            f"{origin['latitude']}, "
            f"{origin['longitude']} | "
            f"uncertainty: {origin['uncertainty_km']:.2f} km"
        )